### ISSUE TITLE
Define grit

### ISSUE THREAD

**Issue by shntnu** [cytomining/cytominer-eval#20]
(Stubs for now, so we can add this documentation to code later)

Grit can be computed in many different contexts:

A replicate's grit is its average similarity to other replicates, z-scored against its similarity to negative control replicates.

A guide's grit is its average similarity to other guides targeting the same gene, z-scored against its similarity to negative control guides.

A compound's grit (in the context of MOA) is its average similarity to other compounds in the same MOA class, z-scored against its similarity to DMSO replicates.

**Comment by gwaygenomics** [comment]
We can also calculate grit at the single cell level (scGrit).

This could have some pretty nifty applications. For example in broadinstitute/grit-benchmark#4, I applied `grit` to a perturb-seq dataset (specifically, from [GEO accession `GSE132080`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE132080)).

> Jost M, Santos DA, Saunders RA, Horlbeck MA et al. Titrating gene expression using libraries of systematically attenuated CRISPR guide RNAs. Nat Biotechnol 2020 Mar;38(3):355-364. PMID: 31932729

A compelling example of scGrit is shown below:

![GSE132080_HSPA5_singlecell_umap_grit](https://user-images.githubusercontent.com/7340421/98568534-30cf1200-227f-11eb-9aef-b95fb2b44a14.png)

**Comment by shntnu** [comment]
This [README](https://github.com/broadinstitute/grit-benchmark/blob/33d0f86847b78dccd503aa962b58ee3330cf1eee/README.md) has a nice explanation.
