### ISSUE TITLE
Adding comparison to mp-value

### ISSUE THREAD

**Issue by koalive** [cytomining/cytominer-eval#25]
Hi there! 
@gwaygenomics as we discussed I am looking on adding the multidimensional perturbation value (mp-value, DOI: 
[10.1177/1087057112469257](https://doi.org/10.1177/1087057112469257)) as another metric to which you could compare the grit score. This actually sounds like solving #23 (the mp-value is basically the Mahalanobis distance to the negative controls on the PCA-reduced space).  
To clarify and make sure this would fit in this project, could you please confirm that these are the steps it would require?

* In `cytominer_eval.operations` define a new operation `mp_value`.
* In `test-evaluate.py`, add a method `test_evaluate_mp_value`.
* In `evaluate.py`, add a case for `operation == "mp_value"`.

Cheers!

**Comment by gwaygenomics** [comment]
That's exactly right @koalive - awesome. Excited to see your contributions!

A couple of additional notes:
* When writing `cytominer_eval.operations.mp_value.py` please follow the current API to the extent possible. This means: 
  * repurposing the [`assign_replicates()`](https://github.com/cytomining/cytominer-eval/blob/6f9d350badd0a18b6c1a76171813aaf9a52f8d9f/cytominer_eval/operations/util.py#L11) function
  * Adding an `mp_value` option to the [`assert_melt()`](https://github.com/cytomining/cytominer-eval/blob/6f9d350badd0a18b6c1a76171813aaf9a52f8d9f/cytominer_eval/transform/util.py#L59) function.

Cheers!

**Comment by gwaygenomics** [comment]
implemented in #26
